### ISSUE TITLE
Set up GitHub Pages

### ISSUE THREAD

**Issue by gdalle** [tfisher013/SuperStreetViewRouter.jl#1]
Your documentation website is ready, all you need to do is activate GitHub Pages and select the branch gh-pages as a source

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch

**Comment by tfisher013** [comment]
Thanks for linking this, @gdalle! I followed the instructions and this should be set up for our repo now.

Could you remind me how to access the documentation website? I recall you showing the one from the HashCode2014 repo in lecture on Tuesday but don't remember how you accessed it.

Thanks!

**Comment by tfisher013** [comment]
Nevermind, @lucpaoli showed me to how access the documentation website.

Closing this issue as it seems to be working.

**Comment by gdalle** [comment]
Yeah GitHub tells you the URL on the settings page
