### ISSUE TITLE
Activate CodeCov

### ISSUE THREAD

**Issue by gdalle** [tfisher013/SuperStreetViewRouter.jl#11]
https://github.com/tfisher013/SuperStreetViewRouter.jl/blob/957bcc0702c7b44fa513bd74399d09ab1939abd0/README.md?plain=1#L6

For this button to be useful, you need to give CodeCov access to your GitHub repo

**Comment by tfisher013** [comment]
CodeCov is now activated on this repo. 

Coverage is currently at 63% and needs to be increased. Closing this issue as activation is complete.
