### ISSUE TITLE
Why this choice of graph structure?

### ISSUE THREAD

**Issue by gdalle** [tfisher013/SuperStreetViewRouter.jl#4]
https://github.com/tfisher013/SuperStreetViewRouter.jl/blob/232445088863e10dff0d41637387377193f2659e/src/SuperStreetViewRouter.jl#L4
This is not criticism, I'm genuinely curious

**Comment by lucpaoli** [comment]
The main answer is it seemed to be the simplest package that allowed us to store the metadata we needed on each edge (i.e. time for constraint check and value for objective function).

It also provides a type of graph ``ValOutDiGraph`` that reduces memory usage by only storing outgoing edges from a given node, which fit well with our requirements.

The other packages considered include:
- SimpleWeightedGraphs - this does not appear to allow for weights that don't subtype real, which is what we required
- MetaGraphs/MetaGraphsNext - seemed overcomplicated for our base requirements, having vertex labels + overall more configurable options. This would allow for greater flexibility, but seemed less "neat" to use.

Finally, in the "benchmarks" of SimpleValueGraphs.jl, they appear to greatly outperform MetaGraphs.

May I ask what package you would have used?

**Comment by lucpaoli** [comment]
I'm going to close this issue for lack of activity. If there are any further questions, please let me know!
