### ISSUE TITLE
Why not use the functions from HashCode2014.jl?

### ISSUE THREAD

**Issue by gdalle** [tfisher013/SuperStreetViewRouter.jl#5]
https://github.com/tfisher013/SuperStreetViewRouter.jl/blob/232445088863e10dff0d41637387377193f2659e/src/util.jl#L8

**Comment by lucpaoli** [comment]
When initially beginning work, we did not notice that HashCode2014 had a function pre-written to do this, so @tfisher013 wrote a small function to do that. It would be easy to switch over, but we haven't done that yet.

I think it would be a good idea to do so to reduce the LoC of the package & tests we will need to write. Opinions @tfisher013 @shelleychoi ?

**Comment by tfisher013** [comment]
Yes, this is my mistake. We should be using the function from HashCode2014. I'll remove the file and close this issue now.

**Comment by tfisher013** [comment]
Function removed with this commit: https://github.com/tfisher013/SuperStreetViewRouter.jl/commit/83347b1302678704f4267f0a55fbe0cfc09ab0f7.
