### ISSUE TITLE
Make `city` an argument

### ISSUE THREAD

**Issue by gdalle** [tfisher013/SuperStreetViewRouter.jl#6]
https://github.com/tfisher013/SuperStreetViewRouter.jl/blob/232445088863e10dff0d41637387377193f2659e/src/functions.jl#L12

**Comment by tfisher013** [comment]
The city variable has been changed to be a function argument with this commit: https://github.com/tfisher013/SuperStreetViewRouter.jl/commit/c1e6632f7639457e6a34093cbc501526cf2c33e8.

Thanks for the feedback :)
