### ISSUE TITLE
Very inefficient check

### ISSUE THREAD

**Issue by gdalle** [tfisher013/SuperStreetViewRouter.jl#7]
https://github.com/tfisher013/SuperStreetViewRouter.jl/blob/232445088863e10dff0d41637387377193f2659e/src/util.jl#L46

**Comment by tfisher013** [comment]
Removed this function as it is no longer used by the solver. See commit https://github.com/tfisher013/SuperStreetViewRouter.jl/commit/5005d941b19d26deeb831e825fd63185394b1142.
