### ISSUE TITLE
Make this container more efficient

### ISSUE THREAD

**Issue by gdalle** [tfisher013/SuperStreetViewRouter.jl#9]
https://github.com/tfisher013/SuperStreetViewRouter.jl/blob/232445088863e10dff0d41637387377193f2659e/src/solver.jl#L28

**Comment by lucpaoli** [comment]
Updated so DefaultDict is instantiated as {Int,Int} rather than {Any,Any} (The default). Could move to work off of inferred types from street.id

**Comment by gdalle** [comment]
You decide when the issue is closed, I'm just here to complain about stuff ;)

**Comment by lucpaoli** [comment]
Further improvement covered by issue #12, closing for now
